models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        data_tests:
          - unique
          - not_null

      - name: host_id
        data_tests:
          - not_null
          - relationships:    # foreign key test 
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt',
                         'Private room',
                         'Shared room',
                         'Hotel room']

  - name: dim_hosts_cleansed
    columns:
      - name: host_id
        data_tests:
          - unique
          - not_null
      - name: host_name
        data_tests:
          - not_null
      - name: is_superhost
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']

  - name: fct_reviews
    columns:
      - name: review_id
        data_tests:
          - dbt_expectations.expect_column_to_exist
